services:
  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  backend:
    build: ./backend
    container_name: backend
    environment:
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
      - FRONT_HOST=${FRONT_HOST}
      - FRONT_PORT=${FRONT_PORT}
    ports:
      - "${BACK_PORT}:8000"
    depends_on:
      - opensearch-node
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - VITE_API_BASE_URL=${BACK_HOST}:${BACK_PORT}
    ports:
      - "${FRONT_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    

volumes:
  opensearch-data: